export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const REQUEST_GET_ALL_ITEMS = 'REQUEST_GET_ALL_ITEMS';
export const SUCCESS_GET_ALL_ITEMS = 'SUCCESS_GET_ALL_ITEMS';
export const FAIL_GET_ALL_ITEMS = 'FAIL_GET_ALL_ITEMS';
