export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
export const SET_MODAL_VISIBILITY = 'SET_MODAL_VISIBILITY';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const REQUEST_GET_ALL_ITEMS = 'REQUEST_GET_ALL_ITEMS';
export const SUCCESS_GET_ALL_ITEMS = 'SUCCESS_GET_ALL_ITEMS';
export const FAIL_GET_ALL_ITEMS = 'FAIL_GET_ALL_ITEMS';

export const REQUEST_ADD_ITEM = 'REQUEST_ADD_ITEM';
export const SUCCESS_ADD_ITEM = 'SUCCESS_ADD_ITEM';
export const FAIL_ADD_ITEM = 'FAIL_ADD_ITEM';

export const REQUEST_EDIT_ITEM = 'REQUEST_EDIT_ITEM';
export const SUCCESS_EDIT_ITEM = 'SUCCESS_EDIT_ITEM';
export const FAIL_EDIT_ITEM = 'FAIL_EDIT_ITEM';

export const REQUEST_DELETE_ITEM = 'REQUEST_DELETE_ITEM';
export const SUCCESS_DELETE_ITEM = 'SUCCESS_DELETE_ITEM';
export const FAIL_DELETE_ITEM = 'FAIL_DELETE_ITEM';
